# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixit', '0002_auto_20170212_0226'),
        ('fixit', '0002_auto_20170212_0228'),
    ]

    operations = [
    ]
